default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['BCB_CARTS_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: bcb_carts_development

test:
  <<: *default
  database: bcb_carts_test

production:
  <<: *default
  database: bcb_carts_production
  url: <%= ENV['DATABASE_URL'] %>
